# Fire22 Enterprise Configuration
# YAML format for complex hierarchical data

name: "Fire22 Enterprise System"
version: "2.0.0-architecture"
description: "Domain-Driven Design implementation with Bun runtime"

author:
  name: "Fire22 Team"
  email: "team@fire22.com"
  organization: "Fire22 Enterprise"

project:
  architecture: "Domain-Driven Design"
  runtime: "Bun v1.x"
  framework: "Crystal Clear Architecture"
  domains:
    - collections
    - balance
    - wager
    - settlement
    - vip
    - user-management

environment:
  production: false
  debug: true
  log_level: "warn"
  timezone: "UTC"
  database:
    type: "SQLite"
    path: "./domain-data.sqlite"
    migrations: "./migrations"

features:
  security_scanner: true
  telemetry: false
  auto_install: true
  coverage_reporting: true
  hot_reload: true

dependencies:
  bun: "^1.0.0"
  typescript: "^5.0.0"
  semver: "^7.0.0"

domains:
  - name: "collections"
    version: "1.0.0"
    description: "Domain collection management"
    enabled: true
  - name: "balance"
    version: "1.0.0"
    description: "Account balance management"
    enabled: true
  - name: "wager"
    version: "1.0.0"
    description: "Wager processing and validation"
    enabled: true

security:
  enterprise_mode: true
  trusted_registries_only: true
  require_audit: true
  policies:
    - "no-typosquatting"
    - "no-malicious-code"
    - "license-compliance"
    - "supply-chain-security"
