name = "crystal-clear-architecture"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
[pages]
# Build configuration
[build]
command = "bun run build"
cwd = "."
output_dir = "dist"

# Environment variables
[vars]
NODE_ENV = "production"
GITHUB_REPO = "nolarose1968-pixel/crystal-clear-architecture"
GITHUB_BRANCH = "main"
CF_PAGES = "1"

# Routes for API endpoints
[[pages_build_config]]
# Build command for the documentation site
build_command = "bun run build:docs"
destination_dir = "docs"

# Custom domain configuration
[[pages_build_config.custom_domain]]
domain = "docs.apexodds.net"
zone_name = "apexodds.net"

# Functions configuration
[pages_build_config.functions]
directory = "functions"

# Analytics and monitoring
[[analytics_engine_datasets]]
binding = "page_analytics"
dataset = "crystal_clear_analytics"

# Rate limiting for API endpoints
# [rate_limiting]
# burst = 100
# period = 60

# CORS configuration
[cors]
origins = ["*"]
methods = ["GET", "HEAD", "OPTIONS", "POST"]
headers = ["*"]
allow_credentials = false
max_age = 86400

# Security headers
[security]
# Content Security Policy
content_security_policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://*.githubusercontent.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.github.com;"

# Development settings
[dev]
port = 8788
local_protocol = "https"

# Custom headers for all responses
[[headers]]
source = "/**"
[headers.headers]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache headers for static assets
[[headers]]
source = "/static/**"
[headers.headers]
Cache-Control = "public, max-age=31536000, immutable"

# Cache headers for docs
[[headers]]
source = "/docs/**"
[headers.headers]
Cache-Control = "public, max-age=3600"

# API headers
[[headers]]
source = "/api/**"
[headers.headers]
Cache-Control = "no-cache"
X-API-Version = "v1"
