/**
 * Auto-generated RSS/Atom feeds content
 * Generated at: 2025-08-28T22:34:22.367Z
 * DO NOT EDIT - This file is auto-generated by scripts/build-feeds-module.ts
 */

export const feedsContent: Record<string, string> = {
  'error-codes-rss.xml': `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
  <title>Fire22 Dashboard - Error Code Registry</title>
  <description>Real-time updates for Fire22 Dashboard error codes, system alerts, and troubleshooting information</description>
  <link>https://dashboard-worker.nolarose2503.workers.dev/feeds/error-codes-rss.xml</link>
  <atom:link href="https://dashboard-worker.nolarose2503.workers.dev/feeds/error-codes-rss.xml" rel="self" type="application/rss+xml"/>
  <language>en-us</language>
  <lastBuildDate>Wed, 28 Jan 2025 00:00:00 GMT</lastBuildDate>
  <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
  <generator>Fire22 Dashboard Error Code System v1.0.0</generator>
  <managingEditor>tech-team@fire22.ag (Fire22 Technology Department)</managingEditor>
  <webMaster>ops-manager@fire22.ag (Fire22 Operations Department)</webMaster>
  <category>Technology</category>
  <category>System Monitoring</category>
  <category>Error Tracking</category>
  <ttl>60</ttl>
  
  <image>
    <url>https://dashboard-worker.nolarose2503.workers.dev/assets/fire22-logo.png</url>
    <title>Fire22 Dashboard</title>
    <link>https://dashboard-worker.nolarose2503.workers.dev/</link>
    <width>144</width>
    <height>144</height>
    <description>Fire22 Dashboard Error Code Registry</description>
  </image>

  <!-- System Errors (E1xxx) - Technology Department -->
  <item>
    <title>🔴 CRITICAL: E1001 - SYSTEM_INIT_FAILED</title>
    <description><![CDATA[
      <h3>System Initialization Failed</h3>
      <p><strong>Department:</strong> Technology Department 💻</p>
      <p><strong>Severity:</strong> CRITICAL</p>
      <p><strong>HTTP Status:</strong> 500</p>
      <p><strong>Description:</strong> Core system components failed to initialize properly during application startup.</p>
      
      <h4>🔍 Common Causes:</h4>
      <ul>
        <li>Insufficient system resources (memory, disk space)</li>
        <li>Missing or corrupted configuration files</li>
        <li>Failed dependency injection</li>
        <li>Database connection failure during startup</li>
        <li>Missing environment variables</li>
      </ul>
      
      <h4>💡 Solutions:</h4>
      <ul>
        <li>Check system resources: <code>free -m && df -h</code></li>
        <li>Verify configuration files syntax and completeness</li>
        <li>Review system logs: <code>journalctl -u fire22-dashboard</code></li>
        <li>Validate environment variables: <code>bun run env:validate</code></li>
        <li>Test database connectivity before startup</li>
      </ul>
      
      <p><strong>📞 Contact:</strong> tech-team@fire22.ag</p>
      <p><strong>📚 Documentation:</strong> <a href="/docs/system/troubleshooting">System Troubleshooting Guide</a></p>
    ]]></description>
    <link>https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E1001</link>
    <guid isPermaLink="true">https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E1001</guid>
    <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
    <category>System</category>
    <category>Critical</category>
    <category>Technology</category>
    <dc:creator>Fire22 Technology Department</dc:creator>
  </item>

  <item>
    <title>🟡 ERROR: E1002 - MEMORY_LIMIT_EXCEEDED</title>
    <description><![CDATA[
      <h3>Memory Limit Exceeded</h3>
      <p><strong>Department:</strong> Technology Department 💻</p>
      <p><strong>Severity:</strong> ERROR</p>
      <p><strong>HTTP Status:</strong> 507</p>
      <p><strong>Description:</strong> Application exceeded allocated memory limits, which can cause system instability.</p>
      
      <h4>🔍 Common Causes:</h4>
      <ul>
        <li>Memory leak in application code</li>
        <li>Insufficient memory allocation</li>
        <li>Large dataset processing without pagination</li>
        <li>Recursive functions causing stack overflow</li>
        <li>Unoptimized database queries loading too much data</li>
      </ul>
      
      <h4>💡 Solutions:</h4>
      <ul>
        <li>Increase memory allocation in configuration</li>
        <li>Implement memory profiling: <code>bun run profile:memory</code></li>
        <li>Optimize data processing with streaming/pagination</li>
        <li>Review and optimize database queries</li>
        <li>Monitor with: <code>bun run monitor:memory</code></li>
      </ul>
      
      <p><strong>📞 Contact:</strong> tech-team@fire22.ag</p>
    ]]></description>
    <link>https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E1002</link>
    <guid isPermaLink="true">https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E1002</guid>
    <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
    <category>System</category>
    <category>Error</category>
    <category>Technology</category>
    <dc:creator>Fire22 Technology Department</dc:creator>
  </item>

  <item>
    <title>🟡 ERROR: E1003 - DIRECTORY_NOT_FOUND</title>
    <description><![CDATA[
      <h3>Required Directory Not Found</h3>
      <p><strong>Department:</strong> Technology Department 💻</p>
      <p><strong>Severity:</strong> ERROR</p>
      <p><strong>HTTP Status:</strong> 404</p>
      <p><strong>Description:</strong> System cannot locate required directory path, preventing file operations.</p>
      
      <h4>🔍 Common Causes:</h4>
      <ul>
        <li>Directory path does not exist in filesystem</li>
        <li>Incorrect relative or absolute path configuration</li>
        <li>Directory was moved or deleted</li>
        <li>Insufficient filesystem permissions</li>
        <li>Case-sensitive filesystem path mismatch</li>
      </ul>
      
      <h4>💡 Solutions:</h4>
      <ul>
        <li>Verify directory exists: <code>ls -la /path/to/directory</code></li>
        <li>Check working directory: <code>pwd</code></li>
        <li>Create missing directory: <code>mkdir -p /path/to/directory</code></li>
        <li>Check permissions: <code>ls -ld /path/to/directory</code></li>
        <li>Use absolute paths instead of relative paths</li>
      </ul>
      
      <p><strong>📞 Contact:</strong> tech-team@fire22.ag</p>
    ]]></description>
    <link>https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E1003</link>
    <guid isPermaLink="true">https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E1003</guid>
    <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
    <category>System</category>
    <category>Error</category>
    <category>Technology</category>
    <dc:creator>Fire22 Technology Department</dc:creator>
  </item>

  <!-- Database Errors (E2xxx) - Technology Department -->
  <item>
    <title>🔴 CRITICAL: E2001 - DB_CONNECTION_FAILED</title>
    <description><![CDATA[
      <h3>Database Connection Failed</h3>
      <p><strong>Department:</strong> Technology Department 💻</p>
      <p><strong>Severity:</strong> CRITICAL</p>
      <p><strong>HTTP Status:</strong> 503</p>
      <p><strong>Description:</strong> Unable to establish connection to database server, preventing all data operations.</p>
      
      <h4>🔍 Common Causes:</h4>
      <ul>
        <li>Database server is down or unreachable</li>
        <li>Invalid connection string or credentials</li>
        <li>Network connectivity issues</li>
        <li>Firewall blocking database port</li>
        <li>Database server resource exhaustion</li>
      </ul>
      
      <h4>💡 Solutions:</h4>
      <ul>
        <li>Check database status: <code>bun run health:database</code></li>
        <li>Test connection: <code>bun run test:db-connection</code></li>
        <li>Verify network connectivity: <code>ping db-host.fire22.ag</code></li>
        <li>Check firewall rules and ports</li>
        <li>Monitor database resources</li>
      </ul>
      
      <p><strong>📞 Contact:</strong> tech-team@fire22.ag | ops-manager@fire22.ag</p>
    ]]></description>
    <link>https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E2001</link>
    <guid isPermaLink="true">https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E2001</guid>
    <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
    <category>Database</category>
    <category>Critical</category>
    <category>Technology</category>
    <dc:creator>Fire22 Technology Department</dc:creator>
  </item>

  <item>
    <title>🟡 ERROR: E2002 - DB_QUERY_TIMEOUT</title>
    <description><![CDATA[
      <h3>Database Query Timeout</h3>
      <p><strong>Department:</strong> Technology Department 💻</p>
      <p><strong>Severity:</strong> ERROR</p>
      <p><strong>HTTP Status:</strong> 504</p>
      <p><strong>Description:</strong> Database query exceeded maximum execution time, indicating performance issues.</p>
      
      <h4>🔍 Common Causes:</h4>
      <ul>
        <li>Inefficient or unoptimized queries</li>
        <li>Missing database indexes</li>
        <li>Large dataset operations without pagination</li>
        <li>Database server resource contention</li>
        <li>Network latency issues</li>
      </ul>
      
      <h4>💡 Solutions:</h4>
      <ul>
        <li>Analyze query performance: <code>EXPLAIN ANALYZE</code></li>
        <li>Add proper indexes for frequently queried columns</li>
        <li>Implement query pagination for large datasets</li>
        <li>Monitor database performance: <code>bun run monitor:db</code></li>
        <li>Optimize slow queries in query log</li>
      </ul>
      
      <p><strong>📞 Contact:</strong> tech-team@fire22.ag</p>
    ]]></description>
    <link>https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E2002</link>
    <guid isPermaLink="true">https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E2002</guid>
    <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
    <category>Database</category>
    <category>Error</category>
    <category>Technology</category>
    <dc:creator>Fire22 Technology Department</dc:creator>
  </item>

  <!-- API Errors (E3xxx) - Technology Department -->
  <item>
    <title>⚠️ WARNING: E3001 - API_UNAUTHORIZED</title>
    <description><![CDATA[
      <h3>Unauthorized API Request</h3>
      <p><strong>Department:</strong> Technology Department 💻 | Customer Support 🎧</p>
      <p><strong>Severity:</strong> WARNING</p>
      <p><strong>HTTP Status:</strong> 401</p>
      <p><strong>Description:</strong> Request lacks valid authentication credentials or token has expired.</p>
      
      <h4>🔍 Common Causes:</h4>
      <ul>
        <li>Missing or invalid API key/token</li>
        <li>Expired authentication token</li>
        <li>Incorrect authentication header format</li>
        <li>Revoked or suspended credentials</li>
        <li>Clock skew causing token validation failure</li>
      </ul>
      
      <h4>💡 Solutions:</h4>
      <ul>
        <li>Verify API key: <code>curl -H "Authorization: Bearer $TOKEN"</code></li>
        <li>Check token expiration and refresh if needed</li>
        <li>Ensure proper header format: <code>Authorization: Bearer [token]</code></li>
        <li>Synchronize system clocks with NTP</li>
        <li>Contact admin if credentials are suspended</li>
      </ul>
      
      <p><strong>📞 Contact:</strong> tech-team@fire22.ag | support@fire22.ag</p>
    ]]></description>
    <link>https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E3001</link>
    <guid isPermaLink="true">https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E3001</guid>
    <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
    <category>API</category>
    <category>Warning</category>
    <category>Technology</category>
    <dc:creator>Fire22 Technology Department</dc:creator>
  </item>

  <item>
    <title>⚠️ WARNING: E3002 - API_RATE_LIMIT_EXCEEDED</title>
    <description><![CDATA[
      <h3>API Rate Limit Exceeded</h3>
      <p><strong>Department:</strong> Technology Department 💻</p>
      <p><strong>Severity:</strong> WARNING</p>
      <p><strong>HTTP Status:</strong> 429</p>
      <p><strong>Description:</strong> Request rate exceeds configured API limits. Implement proper rate limiting handling.</p>
      
      <h4>🔍 Common Causes:</h4>
      <ul>
        <li>Too many requests in short time period</li>
        <li>Missing rate limiting implementation in client</li>
        <li>Inefficient API usage patterns</li>
        <li>Multiple clients using same credentials</li>
        <li>Burst traffic without proper throttling</li>
      </ul>
      
      <h4>💡 Solutions:</h4>
      <ul>
        <li>Implement exponential backoff retry strategy</li>
        <li>Use request caching to reduce API calls</li>
        <li>Implement request queuing and throttling</li>
        <li>Review API usage patterns and optimize</li>
        <li>Consider upgrading rate limit tier</li>
      </ul>
      
      <p><strong>📞 Contact:</strong> tech-team@fire22.ag</p>
    ]]></description>
    <link>https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E3002</link>
    <guid isPermaLink="true">https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E3002</guid>
    <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
    <category>API</category>
    <category>Warning</category>
    <category>Technology</category>
    <dc:creator>Fire22 Technology Department</dc:creator>
  </item>

  <!-- Network Errors (E4xxx) - Technology Department -->
  <item>
    <title>🟡 ERROR: E4001 - NETWORK_TIMEOUT</title>
    <description><![CDATA[
      <h3>Network Request Timeout</h3>
      <p><strong>Department:</strong> Technology Department 💻 | Operations ⚙️</p>
      <p><strong>Severity:</strong> ERROR</p>
      <p><strong>HTTP Status:</strong> 504</p>
      <p><strong>Description:</strong> Network request exceeded timeout duration, indicating connectivity or performance issues.</p>
      
      <h4>🔍 Common Causes:</h4>
      <ul>
        <li>Slow network connection</li>
        <li>Server overload or unresponsive</li>
        <li>DNS resolution delays</li>
        <li>Network congestion or packet loss</li>
        <li>Insufficient timeout configuration</li>
      </ul>
      
      <h4>💡 Solutions:</h4>
      <ul>
        <li>Check network latency: <code>ping fire22.ag</code></li>
        <li>Test DNS resolution: <code>nslookup fire22.ag</code></li>
        <li>Increase request timeout settings appropriately</li>
        <li>Implement retry logic with exponential backoff</li>
        <li>Monitor network performance and routing</li>
      </ul>
      
      <p><strong>📞 Contact:</strong> tech-team@fire22.ag | ops-manager@fire22.ag</p>
    ]]></description>
    <link>https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E4001</link>
    <guid isPermaLink="true">https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E4001</guid>
    <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
    <category>Network</category>
    <category>Error</category>
    <category>Technology</category>
    <dc:creator>Fire22 Technology Department</dc:creator>
  </item>

  <!-- Fire22 Integration Errors (E7xxx) - Operations Department -->
  <item>
    <title>🔴 CRITICAL: E7001 - FIRE22_API_CONNECTION_FAILED</title>
    <description><![CDATA[
      <h3>Fire22 API Connection Failed</h3>
      <p><strong>Department:</strong> Operations Department ⚙️ | Technology Department 💻</p>
      <p><strong>Severity:</strong> CRITICAL</p>
      <p><strong>HTTP Status:</strong> 503</p>
      <p><strong>Description:</strong> Unable to connect to Fire22 sportsbook API, preventing betting operations and data sync.</p>
      
      <h4>🔍 Common Causes:</h4>
      <ul>
        <li>Fire22 API server downtime or maintenance</li>
        <li>Invalid Fire22 API credentials</li>
        <li>Network connectivity to fire22.ag domain</li>
        <li>DNS resolution issues for Fire22 endpoints</li>
        <li>Fire22 API rate limiting or blocking</li>
      </ul>
      
      <h4>💡 Solutions:</h4>
      <ul>
        <li>Check Fire22 API status: <code>curl https://api.fire22.ag/health</code></li>
        <li>Verify Fire22 credentials and authentication</li>
        <li>Test DNS resolution: <code>nslookup api.fire22.ag</code></li>
        <li>Check API rate limits and quotas</li>
        <li>Monitor Fire22 service status page</li>
      </ul>
      
      <p><strong>🚨 Business Impact:</strong> Sportsbook operations disrupted</p>
      <p><strong>📞 Contact:</strong> ops-manager@fire22.ag | tech-team@fire22.ag</p>
    ]]></description>
    <link>https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E7001</link>
    <guid isPermaLink="true">https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E7001</guid>
    <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
    <category>Fire22</category>
    <category>Critical</category>
    <category>Operations</category>
    <dc:creator>Fire22 Operations Department</dc:creator>
  </item>

  <!-- Telegram Integration Errors (E8xxx) - Customer Support Department -->
  <item>
    <title>🟡 ERROR: E8001 - TELEGRAM_BOT_AUTHENTICATION_FAILED</title>
    <description><![CDATA[
      <h3>Telegram Bot Authentication Failed</h3>
      <p><strong>Department:</strong> Customer Support Department 🎧 | Technology Department 💻</p>
      <p><strong>Severity:</strong> ERROR</p>
      <p><strong>HTTP Status:</strong> 401</p>
      <p><strong>Description:</strong> Telegram bot token is invalid or expired, preventing bot functionality and customer communication.</p>
      
      <h4>🔍 Common Causes:</h4>
      <ul>
        <li>Invalid or expired Telegram bot token</li>
        <li>Bot token revoked by Telegram</li>
        <li>Incorrect bot token configuration</li>
        <li>Network connectivity to Telegram API</li>
        <li>Telegram API service disruption</li>
      </ul>
      
      <h4>💡 Solutions:</h4>
      <ul>
        <li>Verify bot token: <code>curl https://api.telegram.org/bot$TOKEN/getMe</code></li>
        <li>Regenerate bot token if compromised via @BotFather</li>
        <li>Check bot token configuration and format</li>
        <li>Test connectivity: <code>ping api.telegram.org</code></li>
        <li>Monitor Telegram API status</li>
      </ul>
      
      <p><strong>🚨 Customer Impact:</strong> Bot notifications and support disabled</p>
      <p><strong>📞 Contact:</strong> support@fire22.ag | tech-team@fire22.ag</p>
    ]]></description>
    <link>https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E8001</link>
    <guid isPermaLink="true">https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E8001</guid>
    <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
    <category>Telegram</category>
    <category>Error</category>
    <category>Customer Support</category>
    <dc:creator>Fire22 Customer Support Department</dc:creator>
  </item>

  <!-- Footer Information -->
  <item>
    <title>📊 Fire22 Dashboard - Error Code Registry Information</title>
    <description><![CDATA[
      <h3>🔧 Error Code Registry System</h3>
      <p>This RSS feed provides real-time updates for Fire22 Dashboard error codes, departmental assignments, and troubleshooting information.</p>
      
      <h4>📈 System Statistics:</h4>
      <ul>
        <li><strong>Total Error Codes:</strong> 9 documented</li>
        <li><strong>Departments Involved:</strong> 3 (Technology, Operations, Customer Support)</li>
        <li><strong>Severity Levels:</strong> Critical (3), Error (4), Warning (2)</li>
        <li><strong>Last Updated:</strong> January 28, 2025</li>
      </ul>
      
      <h4>🏢 Departmental Responsibilities:</h4>
      <ul>
        <li><strong>Technology Department 💻:</strong> System, Database, API, Network errors</li>
        <li><strong>Operations Department ⚙️:</strong> Fire22 integration, business processes</li>
        <li><strong>Customer Support Department 🎧:</strong> Telegram bot, user communications</li>
      </ul>
      
      <h4>🔗 Resources:</h4>
      <ul>
        <li><a href="/docs/error-codes.json">Complete Error Registry (JSON)</a></li>
        <li><a href="/docs/error-code-links.md">Error Code Documentation Links</a></li>
        <li><a href="/src/departments/">Department Information</a></li>
        <li><a href="/docs/api/fire22-endpoints">Fire22 API Documentation</a></li>
      </ul>
      
      <p><strong>🔄 Feed Updates:</strong> This RSS feed is updated automatically when new error codes are added or existing codes are modified.</p>
      <p><strong>📞 Technical Support:</strong> tech-team@fire22.ag</p>
      <p><strong>⚙️ Operations Support:</strong> ops-manager@fire22.ag</p>
    ]]></description>
    <link>https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json</link>
    <guid isPermaLink="true">https://dashboard-worker.nolarose2503.workers.dev/feeds/error-codes-info</guid>
    <pubDate>Wed, 28 Jan 2025 00:00:00 GMT</pubDate>
    <category>Information</category>
    <category>System</category>
    <dc:creator>Fire22 Dashboard System</dc:creator>
  </item>

</channel>
</rss>`,
  'error-codes-atom.xml': `<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en-us">
  <title>Fire22 Dashboard - Error Code Registry</title>
  <subtitle>Real-time updates for Fire22 Dashboard error codes, system alerts, and troubleshooting information</subtitle>
  <link href="https://dashboard-worker.nolarose2503.workers.dev/src/feeds/error-codes-atom.xml" rel="self" type="application/atom+xml"/>
  <link href="https://dashboard-worker.nolarose2503.workers.dev/" rel="alternate" type="text/html"/>
  <id>https://dashboard-worker.nolarose2503.workers.dev/feeds/error-codes</id>
  <updated>2025-01-28T00:00:00Z</updated>
  <generator uri="https://fire22.ag" version="1.0.0">Fire22 Dashboard Error Code System</generator>
  <rights>© 2025 Fire22 Dashboard. All rights reserved.</rights>
  <author>
    <name>Fire22 Technology Department</name>
    <email>tech-team@fire22.ag</email>
  </author>
  <category term="Technology"/>
  <category term="System Monitoring"/>
  <category term="Error Tracking"/>
  <icon>https://dashboard-worker.nolarose2503.workers.dev/assets/fire22-logo.png</icon>
  <logo>https://dashboard-worker.nolarose2503.workers.dev/assets/fire22-logo.png</logo>

  <!-- System Errors (E1xxx) - Technology Department -->
  <entry>
    <title>🔴 CRITICAL: E1001 - SYSTEM_INIT_FAILED</title>
    <link href="https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E1001" rel="alternate" type="text/html"/>
    <id>https://dashboard-worker.nolarose2503.workers.dev/error-codes/E1001</id>
    <published>2025-01-28T00:00:00Z</published>
    <updated>2025-01-28T00:00:00Z</updated>
    <summary type="text">System initialization failed - Core system components failed to initialize properly during application startup.</summary>
    <content type="html"><![CDATA[
      <h3>System Initialization Failed</h3>
      <p><strong>Department:</strong> Technology Department 💻</p>
      <p><strong>Severity:</strong> CRITICAL</p>
      <p><strong>HTTP Status:</strong> 500</p>
      <p><strong>Description:</strong> Core system components failed to initialize properly during application startup.</p>
      
      <h4>🔍 Common Causes:</h4>
      <ul>
        <li>Insufficient system resources (memory, disk space)</li>
        <li>Missing or corrupted configuration files</li>
        <li>Failed dependency injection</li>
        <li>Database connection failure during startup</li>
        <li>Missing environment variables</li>
      </ul>
      
      <h4>💡 Quick Fix Commands:</h4>
      <pre><code>
# Check system resources
free -m && df -h

# Validate environment
bun run env:validate

# Check system logs  
journalctl -u fire22-dashboard

# Test database connectivity
bun run health:database
      </code></pre>
      
      <p><strong>📞 Contact:</strong> tech-team@fire22.ag</p>
      <p><strong>📚 Documentation:</strong> <a href="/docs/system/troubleshooting">System Troubleshooting Guide</a></p>
    ]]></content>
    <author>
      <name>Fire22 Technology Department</name>
      <email>tech-team@fire22.ag</email>
    </author>
    <category term="System"/>
    <category term="Critical"/>
    <category term="Technology"/>
  </entry>

  <entry>
    <title>🔴 CRITICAL: E2001 - DB_CONNECTION_FAILED</title>
    <link href="https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E2001" rel="alternate" type="text/html"/>
    <id>https://dashboard-worker.nolarose2503.workers.dev/error-codes/E2001</id>
    <published>2025-01-28T00:00:00Z</published>
    <updated>2025-01-28T00:00:00Z</updated>
    <summary type="text">Database connection failed - Unable to establish connection to database server, preventing all data operations.</summary>
    <content type="html"><![CDATA[
      <h3>Database Connection Failed</h3>
      <p><strong>Department:</strong> Technology Department 💻</p>
      <p><strong>Severity:</strong> CRITICAL</p>
      <p><strong>HTTP Status:</strong> 503</p>
      <p><strong>Description:</strong> Unable to establish connection to database server, preventing all data operations.</p>
      
      <h4>🔍 Immediate Actions:</h4>
      <pre><code>
# Check database health
bun run health:database

# Test connectivity
ping db-host.fire22.ag

# Verify connection string
bun run test:db-connection

# Check database logs
docker logs fire22-postgres
      </code></pre>
      
      <p><strong>🚨 Impact:</strong> All database operations are blocked</p>
      <p><strong>📞 Emergency Contact:</strong> tech-team@fire22.ag | ops-manager@fire22.ag</p>
    ]]></content>
    <author>
      <name>Fire22 Technology Department</name>
      <email>tech-team@fire22.ag</email>
    </author>
    <category term="Database"/>
    <category term="Critical"/>
    <category term="Technology"/>
  </entry>

  <entry>
    <title>🔴 CRITICAL: E7001 - FIRE22_API_CONNECTION_FAILED</title>
    <link href="https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E7001" rel="alternate" type="text/html"/>
    <id>https://dashboard-worker.nolarose2503.workers.dev/error-codes/E7001</id>
    <published>2025-01-28T00:00:00Z</published>
    <updated>2025-01-28T00:00:00Z</updated>
    <summary type="text">Fire22 API connection failed - Unable to connect to Fire22 sportsbook API, preventing betting operations.</summary>
    <content type="html"><![CDATA[
      <h3>Fire22 API Connection Failed</h3>
      <p><strong>Department:</strong> Operations Department ⚙️ | Technology Department 💻</p>
      <p><strong>Severity:</strong> CRITICAL</p>
      <p><strong>HTTP Status:</strong> 503</p>
      <p><strong>Description:</strong> Unable to connect to Fire22 sportsbook API, preventing betting operations and data sync.</p>
      
      <h4>🔍 Emergency Diagnostics:</h4>
      <pre><code>
# Check Fire22 API status
curl https://api.fire22.ag/health

# Test DNS resolution
nslookup api.fire22.ag

# Verify API credentials
curl -H "Authorization: Bearer $FIRE22_TOKEN" https://api.fire22.ag/auth/verify

# Check rate limits
curl -I https://api.fire22.ag/v1/limits
      </code></pre>
      
      <p><strong>🚨 Business Impact:</strong> Sportsbook operations disrupted, customer betting blocked</p>
      <p><strong>📞 Emergency Escalation:</strong> ops-manager@fire22.ag (Primary) | tech-team@fire22.ag (Technical)</p>
      <p><strong>📈 Monitor:</strong> <a href="/api/fire22/status">Fire22 Integration Dashboard</a></p>
    ]]></content>
    <author>
      <name>Fire22 Operations Department</name>
      <email>ops-manager@fire22.ag</email>
    </author>
    <category term="Fire22"/>
    <category term="Critical"/>
    <category term="Operations"/>
  </entry>

  <entry>
    <title>⚠️ WARNING: E3001 - API_UNAUTHORIZED</title>
    <link href="https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E3001" rel="alternate" type="text/html"/>
    <id>https://dashboard-worker.nolarose2503.workers.dev/error-codes/E3001</id>
    <published>2025-01-28T00:00:00Z</published>
    <updated>2025-01-28T00:00:00Z</updated>
    <summary type="text">Unauthorized API request - Request lacks valid authentication credentials or token has expired.</summary>
    <content type="html"><![CDATA[
      <h3>Unauthorized API Request</h3>
      <p><strong>Department:</strong> Technology Department 💻 | Customer Support 🎧</p>
      <p><strong>Severity:</strong> WARNING</p>
      <p><strong>HTTP Status:</strong> 401</p>
      <p><strong>Description:</strong> Request lacks valid authentication credentials or token has expired.</p>
      
      <h4>🔍 Quick Diagnostics:</h4>
      <pre><code>
# Verify token format
echo $API_TOKEN | base64 -d | jq '.'

# Test authentication
curl -H "Authorization: Bearer $API_TOKEN" https://api.fire22.ag/auth/verify

# Check token expiration
jwt decode $API_TOKEN

# Refresh token if expired
curl -X POST https://api.fire22.ag/auth/refresh
      </code></pre>
      
      <p><strong>👥 User Impact:</strong> API clients experiencing authentication failures</p>
      <p><strong>📞 Contact:</strong> tech-team@fire22.ag | support@fire22.ag</p>
    ]]></content>
    <author>
      <name>Fire22 Technology Department</name>
      <email>tech-team@fire22.ag</email>
    </author>
    <category term="API"/>
    <category term="Warning"/>
    <category term="Technology"/>
  </entry>

  <entry>
    <title>🟡 ERROR: E8001 - TELEGRAM_BOT_AUTHENTICATION_FAILED</title>
    <link href="https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json#E8001" rel="alternate" type="text/html"/>
    <id>https://dashboard-worker.nolarose2503.workers.dev/error-codes/E8001</id>
    <published>2025-01-28T00:00:00Z</published>
    <updated>2025-01-28T00:00:00Z</updated>
    <summary type="text">Telegram bot authentication failed - Bot token is invalid or expired, preventing customer communication.</summary>
    <content type="html"><![CDATA[
      <h3>Telegram Bot Authentication Failed</h3>
      <p><strong>Department:</strong> Customer Support Department 🎧 | Technology Department 💻</p>
      <p><strong>Severity:</strong> ERROR</p>
      <p><strong>HTTP Status:</strong> 401</p>
      <p><strong>Description:</strong> Telegram bot token is invalid or expired, preventing bot functionality and customer communication.</p>
      
      <h4>🔍 Bot Diagnostics:</h4>
      <pre><code>
# Verify bot token
curl https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/getMe

# Check bot permissions
curl https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/getMyCommands

# Test webhook
curl https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/getWebhookInfo

# Monitor bot logs
bun run logs:telegram-bot
      </code></pre>
      
      <p><strong>👥 Customer Impact:</strong> Bot notifications disabled, customer support affected</p>
      <p><strong>📞 Primary Contact:</strong> support@fire22.ag</p>
      <p><strong>🔧 Technical Support:</strong> tech-team@fire22.ag</p>
      <p><strong>🤖 Bot Management:</strong> Contact @BotFather for token issues</p>
    ]]></content>
    <author>
      <name>Fire22 Customer Support Department</name>
      <email>support@fire22.ag</email>
    </author>
    <category term="Telegram"/>
    <category term="Error"/>
    <category term="Customer Support"/>
  </entry>

  <!-- Feed Information Entry -->
  <entry>
    <title>📊 Fire22 Dashboard - Error Code Registry Feed Information</title>
    <link href="https://dashboard-worker.nolarose2503.workers.dev/docs/error-codes.json" rel="alternate" type="text/html"/>
    <id>https://dashboard-worker.nolarose2503.workers.dev/feeds/error-codes-info</id>
    <published>2025-01-28T00:00:00Z</published>
    <updated>2025-01-28T00:00:00Z</updated>
    <summary type="text">Fire22 Dashboard Error Code Registry system information and departmental assignments.</summary>
    <content type="html"><![CDATA[
      <h3>🔧 Error Code Registry System</h3>
      <p>This Atom feed provides real-time updates for Fire22 Dashboard error codes with departmental assignments and comprehensive troubleshooting information.</p>
      
      <h4>📈 Registry Statistics:</h4>
      <table style="border-collapse: collapse; width: 100%;">
        <tr style="background-color: #f0f9ff; border: 1px solid #0ea5e9;">
          <th style="padding: 8px; border: 1px solid #0ea5e9;">Metric</th>
          <th style="padding: 8px; border: 1px solid #0ea5e9;">Value</th>
        </tr>
        <tr>
          <td style="padding: 8px; border: 1px solid #e0e7ff;">Total Error Codes</td>
          <td style="padding: 8px; border: 1px solid #e0e7ff;"><strong>9 documented</strong></td>
        </tr>
        <tr style="background-color: #f8fafc;">
          <td style="padding: 8px; border: 1px solid #e0e7ff;">Departments Involved</td>
          <td style="padding: 8px; border: 1px solid #e0e7ff;"><strong>3 departments</strong></td>
        </tr>
        <tr>
          <td style="padding: 8px; border: 1px solid #e0e7ff;">Severity Levels</td>
          <td style="padding: 8px; border: 1px solid #e0e7ff;">Critical (3), Error (4), Warning (2)</td>
        </tr>
        <tr style="background-color: #f8fafc;">
          <td style="padding: 8px; border: 1px solid #e0e7ff;">Last Updated</td>
          <td style="padding: 8px; border: 1px solid #e0e7ff;">January 28, 2025</td>
        </tr>
      </table>
      
      <h4>🏢 Department Responsibilities:</h4>
      <ul>
        <li><strong>💻 Technology Department:</strong> E1xxx (System), E2xxx (Database), E3xxx (API), E4xxx (Network)</li>
        <li><strong>⚙️ Operations Department:</strong> E7xxx (Fire22 Integration), Business processes</li>
        <li><strong>🎧 Customer Support:</strong> E8xxx (Telegram Bot), User communications</li>
      </ul>
      
      <h4>🔗 Resources & Documentation:</h4>
      <ul>
        <li><a href="/docs/error-codes.json">📄 Complete Error Registry (JSON)</a></li>
        <li><a href="/docs/error-code-links.md">🔗 Error Code Documentation Links</a></li>
        <li><a href="/src/departments/">🏢 Department Information</a></li>
        <li><a href="/docs/api/fire22-endpoints">🏆 Fire22 API Documentation</a></li>
        <li><a href="/src/feeds/error-codes-rss.xml">📡 RSS Feed Version</a></li>
      </ul>
      
      <h4>🔄 Feed Features:</h4>
      <ul>
        <li>Real-time error code updates</li>
        <li>Departmental assignments and contact information</li>
        <li>Command-line diagnostic tools</li>
        <li>Business impact assessments</li>
        <li>Escalation procedures</li>
      </ul>
      
      <p><strong>📞 Support Contacts:</strong></p>
      <ul>
        <li>Technical Support: tech-team@fire22.ag</li>
        <li>Operations Support: ops-manager@fire22.ag</li>
        <li>Customer Support: support@fire22.ag</li>
      </ul>
    ]]></content>
    <author>
      <name>Fire22 Dashboard System</name>
      <email>tech-team@fire22.ag</email>
    </author>
    <category term="Information"/>
    <category term="System"/>
    <category term="Documentation"/>
  </entry>

</feed>`,
  'team-announcements-rss.xml': `<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>🏢 Fire22 Team Announcements</title>
    <link>https://dashboard-worker.fire22.workers.dev/feeds/team-announcements</link>
    <description>Official Fire22 team announcements, leadership appointments, and organizational updates</description>
    <language>en-us</language>
    <lastBuildDate>Wed, 28 Aug 2025 20:00:00 GMT</lastBuildDate>
    <managingEditor>communications@fire22.ag (Fire22 Communications Department)</managingEditor>
    <webMaster>tech@fire22.ag (Fire22 Tech Team)</webMaster>
    <category>Team Announcements</category>
    <category>Leadership</category>
    <category>Organization</category>
    <ttl>60</ttl>
    <atom:link href="https://dashboard-worker.fire22.workers.dev/feeds/team-announcements-rss.xml" rel="self" type="application/rss+xml" />

    <image>
      <url>https://dashboard-worker.nolarose2503.workers.dev/assets/fire22-logo.png</url>
      <title>Fire22 Team Announcements</title>
      <link>https://dashboard-worker.nolarose2503.workers.dev/</link>
      <width>144</width>
      <height>144</height>
      <description>Fire22 Team Announcements Feed</description>
    </image>

    <!-- 👑 NEW APPOINTMENT: Vinny2times as Head of VIP Management -->
    <item>
      <title>👑 NEW APPOINTMENT: Vinny2times Named Head of VIP Management</title>
      <link>https://dashboard-worker.fire22.workers.dev/announcements/vinny2times-vip-head</link>
      <description><![CDATA[
        <h2>👑 Leadership Appointment: VIP Management Department</h2>
        
        <p><strong>Effective Date:</strong> August 28, 2025</p>
        <p><strong>Department:</strong> VIP Management 💎</p>
        <p><strong>New Role:</strong> Head of VIP Management</p>
        
        <h3>🎯 Announcement Details:</h3>
        <p>Fire22 is pleased to announce the appointment of <strong>Vinny2times</strong> as Head of VIP Management, effective immediately.</p>
        
        <h4>👤 Contact Information:</h4>
        <ul>
          <li>📧 Email: <strong>vinny2times@vip.fire22</strong></li>
          <li>💬 Slack: <strong>@vinny2times</strong></li>
          <li>📱 Telegram: <strong>@fire22_vip</strong></li>
          <li>📞 Phone: <strong>+1-555-0950</strong></li>
        </ul>
        
        <h4>🏆 Key Responsibilities:</h4>
        <ul>
          <li>🌟 VIP Tier 3 (Concierge) customer management</li>
          <li>💎 High-roller relationship management</li>
          <li>👑 VIP escalation handling and resolution</li>
          <li>🎪 Exclusive VIP events and benefits coordination</li>
          <li>📊 VIP program strategy and optimization</li>
        </ul>
        
        <h4>🎯 VIP Service Tier Integration:</h4>
        <p>Vinny2times will oversee our premium service offerings:</p>
        <ul>
          <li><strong>Tier 3 VIP Concierge:</strong> $250K+ lifetime customers</li>
          <li><strong>Response Time:</strong> 15-30 minutes dedicated support</li>
          <li><strong>Benefits:</strong> 1.5% fee discount, 3x limits, personal manager</li>
          <li><strong>White-glove Service:</strong> Complete concierge experience</li>
        </ul>
        
        <h4>📞 Contact Channels:</h4>
        <p>VIP customers and team members can reach Vinny2times through:</p>
        <ul>
          <li>🚨 <strong>VIP Escalation Portal:</strong> https://vinny2times.fire22.workers.dev/escalation/</li>
          <li>💎 <strong>High Roller Review:</strong> https://vinny2times.fire22.workers.dev/high-roller-review/</li>
          <li>📱 <strong>Telegram VIP Channel:</strong> @fire22_vip</li>
          <li>📋 <strong>Direct Scheduling:</strong> https://vinny2times.fire22.workers.dev/schedule/</li>
        </ul>
        
        <p><em>All VIP-related inquiries should now be directed to Vinny2times and his team.</em></p>
        
        <hr/>
        <p><strong>🤖 Generated by Fire22 Communications Department</strong></p>
        <p><strong>📅 Published:</strong> August 28, 2025, 8:00 PM GMT</p>
      ]]></description>
      <pubDate>Wed, 28 Aug 2025 20:00:00 GMT</pubDate>
      <guid>fire22-announcement-vinny2times-vip-head-20250828</guid>
      <category>Leadership Appointments</category>
      <category>VIP Management</category>
      <category>Team Updates</category>
    </item>

    <!-- Welcome Message Template for Future Announcements -->
    <item>
      <title>📋 Team Announcements Feed Active</title>
      <link>https://dashboard-worker.fire22.workers.dev/feeds/team-announcements</link>
      <description><![CDATA[
        <h2>🏢 Fire22 Team Announcements RSS Feed</h2>
        <p>This feed provides official Fire22 team announcements, leadership appointments, and organizational updates.</p>
        
        <h4>📡 Subscribe to stay updated on:</h4>
        <ul>
          <li>👥 New team member appointments</li>
          <li>🏆 Leadership changes and promotions</li>
          <li>🏢 Department restructuring</li>
          <li>🎯 Strategic initiatives and updates</li>
          <li>📈 Organizational milestones</li>
        </ul>
        
        <p><strong>Feed URL:</strong> https://dashboard-worker.fire22.workers.dev/feeds/team-announcements-rss.xml</p>
      ]]></description>
      <pubDate>Wed, 28 Aug 2025 19:00:00 GMT</pubDate>
      <guid>fire22-team-announcements-feed-active-20250828</guid>
      <category>System Updates</category>
    </item>

  </channel>
</rss>`,
  'team-announcements-atom.xml': `<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>🏢 Fire22 Team Announcements</title>
  <link href="https://dashboard-worker.fire22.workers.dev/feeds/team-announcements-atom.xml" rel="self"/>
  <link href="https://dashboard-worker.fire22.workers.dev/"/>
  <id>https://dashboard-worker.fire22.workers.dev/feeds/team-announcements</id>
  <updated>2025-08-28T20:00:00Z</updated>
  <subtitle>Official Fire22 team announcements, leadership appointments, and organizational updates</subtitle>
  <generator>Fire22 Communications System v1.0.0</generator>
  <author>
    <name>Fire22 Communications Department</name>
    <email>communications@fire22.ag</email>
  </author>

  <entry>
    <title>👑 NEW APPOINTMENT: Vinny2times Named Head of VIP Management</title>
    <link href="https://dashboard-worker.fire22.workers.dev/announcements/vinny2times-vip-head"/>
    <id>https://dashboard-worker.fire22.workers.dev/announcements/vinny2times-vip-head</id>
    <updated>2025-08-28T20:00:00Z</updated>
    <category term="Leadership Appointments"/>
    <category term="VIP Management"/>
    <category term="Team Updates"/>
    <author>
      <name>Fire22 Communications Department</name>
      <email>communications@fire22.ag</email>
    </author>
    <summary>Fire22 announces the appointment of Vinny2times as Head of VIP Management, overseeing Tier 3 VIP Concierge services.</summary>
    <content type="html"><![CDATA[
      <h2>👑 Leadership Appointment: VIP Management Department</h2>
      
      <p><strong>Effective Date:</strong> August 28, 2025</p>
      <p><strong>Department:</strong> VIP Management 💎</p>
      <p><strong>New Role:</strong> Head of VIP Management</p>
      
      <h3>🎯 Announcement Details:</h3>
      <p>Fire22 is pleased to announce the appointment of <strong>Vinny2times</strong> as Head of VIP Management, effective immediately.</p>
      
      <h4>👤 Contact Information:</h4>
      <ul>
        <li>📧 Email: <strong>vinny2times@vip.fire22</strong></li>
        <li>💬 Slack: <strong>@vinny2times</strong></li>
        <li>📱 Telegram: <strong>@fire22_vip</strong></li>
        <li>📞 Phone: <strong>+1-555-0950</strong></li>
      </ul>
      
      <h4>🏆 Key Responsibilities:</h4>
      <ul>
        <li>🌟 VIP Tier 3 (Concierge) customer management</li>
        <li>💎 High-roller relationship management</li>
        <li>👑 VIP escalation handling and resolution</li>
        <li>🎪 Exclusive VIP events and benefits coordination</li>
        <li>📊 VIP program strategy and optimization</li>
      </ul>
      
      <h4>🎯 VIP Service Tier Integration:</h4>
      <p>Vinny2times will oversee our premium service offerings:</p>
      <ul>
        <li><strong>Tier 3 VIP Concierge:</strong> $250K+ lifetime customers</li>
        <li><strong>Response Time:</strong> 15-30 minutes dedicated support</li>
        <li><strong>Benefits:</strong> 1.5% fee discount, 3x limits, personal manager</li>
        <li><strong>White-glove Service:</strong> Complete concierge experience</li>
      </ul>
      
      <h4>📞 Contact Channels:</h4>
      <p>VIP customers and team members can reach Vinny2times through:</p>
      <ul>
        <li>🚨 <strong>VIP Escalation Portal:</strong> https://vinny2times.fire22.workers.dev/escalation/</li>
        <li>💎 <strong>High Roller Review:</strong> https://vinny2times.fire22.workers.dev/high-roller-review/</li>
        <li>📱 <strong>Telegram VIP Channel:</strong> @fire22_vip</li>
        <li>📋 <strong>Direct Scheduling:</strong> https://vinny2times.fire22.workers.dev/schedule/</li>
      </ul>
      
      <p><em>All VIP-related inquiries should now be directed to Vinny2times and his team.</em></p>
      
      <hr/>
      <p><strong>🤖 Generated by Fire22 Communications Department</strong></p>
      <p><strong>📅 Published:</strong> August 28, 2025, 8:00 PM GMT</p>
    ]]></content>
  </entry>

  <entry>
    <title>📋 Team Announcements Feed Active</title>
    <link href="https://dashboard-worker.fire22.workers.dev/feeds/team-announcements"/>
    <id>https://dashboard-worker.fire22.workers.dev/feeds/team-announcements-init</id>
    <updated>2025-08-28T19:00:00Z</updated>
    <category term="System Updates"/>
    <author>
      <name>Fire22 Communications Department</name>
      <email>communications@fire22.ag</email>
    </author>
    <summary>Fire22 Team Announcements RSS/Atom feed is now active for official team updates and leadership appointments.</summary>
    <content type="html"><![CDATA[
      <h2>🏢 Fire22 Team Announcements Feed</h2>
      <p>This feed provides official Fire22 team announcements, leadership appointments, and organizational updates.</p>
      
      <h4>📡 Subscribe to stay updated on:</h4>
      <ul>
        <li>👥 New team member appointments</li>
        <li>🏆 Leadership changes and promotions</li>
        <li>🏢 Department restructuring</li>
        <li>🎯 Strategic initiatives and updates</li>
        <li>📈 Organizational milestones</li>
      </ul>
      
      <p><strong>RSS Feed:</strong> https://dashboard-worker.fire22.workers.dev/feeds/team-announcements-rss.xml</p>
      <p><strong>Atom Feed:</strong> https://dashboard-worker.fire22.workers.dev/feeds/team-announcements-atom.xml</p>
    ]]></content>
  </entry>

</feed>`,
  'critical-errors-alert.xml': `<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>🚨 Fire22 Dashboard - Critical Error Alerts</title>
    <link>https://dashboard-worker.fire22.workers.dev/feeds/critical-errors</link>
    <description>Real-time critical error notifications for Fire22 Dashboard Worker system requiring immediate attention</description>
    <language>en-us</language>
    <lastBuildDate>Wed, 28 Aug 2025 19:45:00 GMT</lastBuildDate>
    <managingEditor>system@fire22.ag (Fire22 System Monitor)</managingEditor>
    <webMaster>tech@fire22.ag (Fire22 Tech Team)</webMaster>
    <category>System Alerts</category>
    <ttl>5</ttl>
    <atom:link href="https://dashboard-worker.fire22.workers.dev/feeds/critical-errors.xml" rel="self" type="application/rss+xml" />

    <!-- 🚨 CRITICAL: Fire22 API Authorization Failure -->
    <item>
      <title>🚨 CRITICAL: E7001 - Fire22 API Unauthorized - Data Extraction Completely Blocked</title>
      <link>https://dashboard-worker.fire22.workers.dev/error/E7001</link>
      <description><![CDATA[
        <h2>🚨 URGENT: Fire22 Data Extraction Completely Blocked</h2>
        
        <p><strong>Error Code:</strong> E7001 - FIRE22_API_UNAUTHORIZED</p>
        <p><strong>Severity:</strong> CRITICAL</p>
        <p><strong>Status:</strong> 401 Unauthorized on ALL Fire22 API endpoints</p>
        
        <h3>🔴 Immediate Impact:</h3>
        <ul>
          <li>❌ Customer data sync (2,600+ records) - BLOCKED</li>
          <li>❌ Agent hierarchy extraction - BLOCKED</li>
          <li>❌ Transaction history retrieval - BLOCKED</li>
          <li>❌ Betting data extraction - BLOCKED</li>
          <li>❌ Live wager monitoring - BLOCKED</li>
        </ul>

        <h3>🎯 Required Action:</h3>
        <p><strong>Security Team:</strong> Provide valid Fire22 API authentication credentials immediately</p>
        <p><strong>Fire22 Team:</strong> Confirm API access permissions and endpoint configuration</p>
        
        <h3>📊 Current Status:</h3>
        <ul>
          <li>Infrastructure: 75% ready (waiting for credentials)</li>
          <li>Data extraction: 0% complete (blocked by authentication)</li>
          <li>System impact: Complete data flow stoppage</li>
        </ul>

        <p><strong>Next Steps:</strong> Contact security team immediately for Fire22 API credentials</p>
      ]]></description>
      <author>system@fire22.ag (Fire22 System Monitor)</author>
      <category>Critical</category>
      <category>Fire22</category>
      <category>Authentication</category>
      <category>Data Extraction</category>
      <guid isPermaLink="true">https://dashboard-worker.fire22.workers.dev/error/E7001</guid>
      <pubDate>Wed, 28 Aug 2025 19:45:00 GMT</pubDate>
    </item>

    <!-- 🚨 CRITICAL: Credential Storage Failed -->
    <item>
      <title>🚨 CRITICAL: E7002 - Bun.secrets Credential Storage Not Functioning</title>
      <link>https://dashboard-worker.fire22.workers.dev/error/E7002</link>
      <description><![CDATA[
        <h2>🔐 CRITICAL: Secure Credential Storage System Down</h2>
        
        <p><strong>Error Code:</strong> E7002 - FIRE22_CREDENTIALS_STORAGE_FAILED</p>
        <p><strong>Severity:</strong> CRITICAL</p>
        <p><strong>Issue:</strong> Bun.secrets.get() returning undefined</p>
        
        <h3>🔴 System Impact:</h3>
        <ul>
          <li>❌ Cannot store Fire22 API credentials securely</li>
          <li>❌ Cannot retrieve stored authentication tokens</li>
          <li>❌ Multi-environment credential management broken</li>
          <li>❌ Security compliance at risk</li>
        </ul>

        <h3>🎯 Required Action:</h3>
        <p><strong>Infrastructure Team:</strong> Verify Bun.secrets and OS credential manager access</p>
        <p><strong>Security Team:</strong> Validate credential storage policies and permissions</p>
        
        <h3>🔧 Possible Causes:</h3>
        <ul>
          <li>OS credential manager (Keychain/libsecret/CredMan) access denied</li>
          <li>Missing Bun runtime permissions</li>
          <li>Credential storage service not running</li>
        </ul>

        <p><strong>Temporary Workaround:</strong> Environment variables (security risk)</p>
      ]]></description>
      <author>system@fire22.ag (Fire22 System Monitor)</author>
      <category>Critical</category>
      <category>Security</category>
      <category>Credentials</category>
      <category>Infrastructure</category>
      <guid isPermaLink="true">https://dashboard-worker.fire22.workers.dev/error/E7002</guid>
      <pubDate>Wed, 28 Aug 2025 19:44:00 GMT</pubDate>
    </item>

    <!-- 🚨 CRITICAL: Database Connection Failed -->
    <item>
      <title>🚨 CRITICAL: E7003 - Fire22 Database Not Connected - Local Storage Blocked</title>
      <link>https://dashboard-worker.fire22.workers.dev/error/E7003</link>
      <description><![CDATA[
        <h2>🗄️ CRITICAL: Local Data Storage System Down</h2>
        
        <p><strong>Error Code:</strong> E7003 - FIRE22_DATABASE_NOT_CONNECTED</p>
        <p><strong>Severity:</strong> CRITICAL</p>
        <p><strong>Issue:</strong> SQLite database connection failed</p>
        
        <h3>🔴 Data Storage Impact:</h3>
        <ul>
          <li>❌ Local Fire22 data storage - BLOCKED</li>
          <li>❌ Customer repository operations - FAILED</li>
          <li>❌ Agent hierarchy caching - UNAVAILABLE</li>
          <li>❌ Transaction logging - DISABLED</li>
          <li>❌ Betting data persistence - BLOCKED</li>
        </ul>

        <h3>🎯 Required Action:</h3>
        <p><strong>Database Team:</strong> Initialize SQLite database connection</p>
        <p><strong>Infrastructure Team:</strong> Verify database file permissions and disk space</p>
        
        <h3>🔧 Immediate Solutions:</h3>
        <ul>
          <li>Run: <code>bun run scripts/verify-fire22-database.ts</code></li>
          <li>Check permissions: <code>ls -la dashboard.db</code></li>
          <li>Test connection: <code>sqlite3 dashboard.db '.tables'</code></li>
        </ul>

        <p><strong>Database Schema:</strong> Ready and waiting for connection</p>
      ]]></description>
      <author>system@fire22.ag (Fire22 System Monitor)</author>
      <category>Critical</category>
      <category>Database</category>
      <category>SQLite</category>
      <category>Storage</category>
      <guid isPermaLink="true">https://dashboard-worker.fire22.workers.dev/error/E7003</guid>
      <pubDate>Wed, 28 Aug 2025 19:43:00 GMT</pubDate>
    </item>

    <!-- ⚠️  ERROR: KV Namespaces Missing -->
    <item>
      <title>⚠️ ERROR: E7004 - Cloudflare KV Namespaces Missing - Performance Impact</title>
      <link>https://dashboard-worker.fire22.workers.dev/error/E7004</link>
      <description><![CDATA[
        <h2>⚡ ERROR: Performance Caching System Unavailable</h2>
        
        <p><strong>Error Code:</strong> E7004 - CLOUDFLARE_KV_NAMESPACES_MISSING</p>
        <p><strong>Severity:</strong> ERROR (Non-blocking but performance impacting)</p>
        <p><strong>Issue:</strong> KV namespace IDs not configured in wrangler.toml</p>
        
        <h3>🟡 Performance Impact:</h3>
        <ul>
          <li>⚠️ Fire22 API response caching - DISABLED</li>
          <li>⚠️ Authentication token caching - DISABLED</li>
          <li>⚠️ Registry package caching - DISABLED</li>
          <li>⚠️ Slower API response times (no cache hits)</li>
        </ul>

        <h3>🎯 Required Action:</h3>
        <p><strong>DevOps Team:</strong> Create and configure Cloudflare KV namespaces</p>
        <p><strong>Infrastructure Team:</strong> Update wrangler.toml with KV namespace IDs</p>
        
        <h3>🔧 Setup Commands:</h3>
        <ul>
          <li><code>wrangler kv:namespace create fire22-data-cache</code></li>
          <li><code>wrangler kv:namespace create fire22-auth-cache</code></li>
          <li><code>wrangler kv:namespace create fire22-registry-cache</code></li>
        </ul>

        <p><strong>Priority:</strong> Medium (system works but slower without caching)</p>
      ]]></description>
      <author>system@fire22.ag (Fire22 System Monitor)</author>
      <category>Error</category>
      <category>Performance</category>
      <category>Cloudflare</category>
      <category>KV Storage</category>
      <guid isPermaLink="true">https://dashboard-worker.fire22.workers.dev/error/E7004</guid>
      <pubDate>Wed, 28 Aug 2025 19:42:00 GMT</pubDate>
    </item>

    <!-- 📊 System Status Summary -->
    <item>
      <title>📊 Fire22 Dashboard System Status - Multiple Critical Issues Detected</title>
      <link>https://dashboard-worker.fire22.workers.dev/status</link>
      <description><![CDATA[
        <h2>🔍 Current System Readiness Assessment</h2>
        
        <h3>📈 Overall Readiness Score: 55/100</h3>
        <p><strong>Status:</strong> ❌ NOT READY - Significant issues blocking operations</p>
        
        <h3>✅ Infrastructure Ready:</h3>
        <ul>
          <li>✅ Local SQLite schema (Fire22 tables configured)</li>
          <li>✅ Cloudflare D1 databases (multi-environment)</li>
          <li>✅ R2 archive storage (7-year retention configured)</li>
          <li>✅ DNS optimization (sub-millisecond resolution)</li>
          <li>✅ Security architecture (Bun.secrets integration)</li>
        </ul>

        <h3>❌ Critical Blockers:</h3>
        <ul>
          <li>❌ <strong>E7001:</strong> Fire22 API 401 Unauthorized (BLOCKS ALL DATA EXTRACTION)</li>
          <li>❌ <strong>E7002:</strong> Bun.secrets not functioning (BLOCKS SECURE CREDENTIALS)</li>
          <li>❌ <strong>E7003:</strong> Database not connected (BLOCKS LOCAL STORAGE)</li>
          <li>⚠️ <strong>E7004:</strong> KV namespaces missing (IMPACTS PERFORMANCE)</li>
        </ul>

        <h3>🎯 Immediate Actions Required:</h3>
        <ol>
          <li><strong>Security Team:</strong> Provide Fire22 API credentials (E7001)</li>
          <li><strong>Infrastructure Team:</strong> Fix Bun.secrets access (E7002)</li>
          <li><strong>Database Team:</strong> Initialize SQLite connection (E7003)</li>
          <li><strong>DevOps Team:</strong> Configure KV namespaces (E7004)</li>
        </ol>

        <p><strong>Data Extraction Status:</strong> 0% complete - Completely blocked by authentication issues</p>
        <p><strong>Expected Resolution Time:</strong> 2-4 hours with proper credentials</p>
      ]]></description>
      <author>system@fire22.ag (Fire22 System Monitor)</author>
      <category>System Status</category>
      <category>Critical</category>
      <category>Assessment</category>
      <guid isPermaLink="true">https://dashboard-worker.fire22.workers.dev/status</guid>
      <pubDate>Wed, 28 Aug 2025 19:40:00 GMT</pubDate>
    </item>

  </channel>
</rss>`,
  'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>📡 Fire22 Dashboard - RSS & Atom Feeds</title>
    <link rel="alternate" type="application/rss+xml" title="Fire22 Error Code Registry" href="error-codes-rss.xml">
    <link rel="alternate" type="application/atom+xml" title="Fire22 Error Code Registry" href="error-codes-atom.xml">
    <link rel="alternate" type="application/rss+xml" title="Fire22 Team Announcements" href="team-announcements-rss.xml">
    <link rel="alternate" type="application/atom+xml" title="Fire22 Team Announcements" href="team-announcements-atom.xml">
    <style>
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: 'SF Mono', 'Monaco', 'Inconsolata', 'Fira Code', monospace;
            background: linear-gradient(135deg, #0a0e27 0%, #151932 50%, #1a1f3a 100%);
            color: #e0e6ed;
            min-height: 100vh;
            line-height: 1.6;
        }

        .header {
            background: rgba(10, 14, 39, 0.9);
            border-bottom: 2px solid rgba(64, 224, 208, 0.3);
            padding: 40px 20px;
            text-align: center;
            backdrop-filter: blur(20px);
            position: sticky;
            top: 0;
            z-index: 100;
        }

        .header h1 {
            font-size: clamp(28px, 5vw, 42px);
            background: linear-gradient(135deg, #ff6b35, #f7931e, #ff6b35);
            background-size: 200% 200%;
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 15px;
            animation: header-glow 4s ease-in-out infinite;
        }

        @keyframes header-glow {
            0%, 100% { background-position: 0% 50%; }
            50% { background-position: 100% 50%; }
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 40px 20px;
        }

        .breadcrumb {
            margin-bottom: 30px;
            padding: 20px 0;
        }

        .breadcrumb a {
            color: #9ca3af;
            text-decoration: none;
            transition: color 0.2s ease;
        }

        .breadcrumb a:hover {
            color: #40e0d0;
        }

        .breadcrumb-separator {
            margin: 0 15px;
            color: #6b7280;
        }

        .breadcrumb-current {
            color: #40e0d0;
            font-weight: 600;
        }

        .feeds-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(500px, 1fr));
            gap: 30px;
            margin-bottom: 40px;
        }

        .feed-card {
            background: rgba(10, 14, 39, 0.7);
            border: 2px solid rgba(64, 224, 208, 0.2);
            border-radius: 20px;
            padding: 30px;
            backdrop-filter: blur(15px);
            transition: all 0.4s ease;
            position: relative;
            overflow: hidden;
        }

        .feed-card::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 4px;
            background: var(--feed-gradient);
            transition: height 0.3s ease;
        }

        .feed-card:hover::before {
            height: 8px;
        }

        .feed-card:hover {
            transform: translateY(-8px) scale(1.02);
            border-color: var(--feed-primary);
            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.4),
                        0 0 30px var(--feed-shadow);
        }

        .feed-rss {
            --feed-primary: #ff6b35;
            --feed-gradient: linear-gradient(135deg, #ff6b35, #f7931e);
            --feed-shadow: rgba(255, 107, 53, 0.3);
        }

        .feed-atom {
            --feed-primary: #10b981;
            --feed-gradient: linear-gradient(135deg, #10b981, #059669);
            --feed-shadow: rgba(16, 185, 129, 0.3);
        }

        .feed-header {
            display: flex;
            align-items: center;
            gap: 20px;
            margin-bottom: 20px;
        }

        .feed-icon {
            width: 60px;
            height: 60px;
            border-radius: 12px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 30px;
            background: var(--feed-gradient);
            color: white;
            box-shadow: 0 8px 25px var(--feed-shadow);
        }

        .feed-title {
            flex: 1;
        }

        .feed-name {
            font-size: 24px;
            font-weight: bold;
            color: var(--feed-primary);
            margin-bottom: 8px;
        }

        .feed-description {
            font-size: 14px;
            color: #9ca3af;
        }

        .feed-details {
            margin: 20px 0;
        }

        .feed-details p {
            margin-bottom: 10px;
            color: #d1d5db;
        }

        .feed-features {
            margin: 20px 0;
        }

        .feed-features h4 {
            color: var(--feed-primary);
            margin-bottom: 10px;
            font-size: 16px;
        }

        .feed-features ul {
            list-style: none;
            padding-left: 0;
        }

        .feed-features li {
            padding: 5px 0;
            color: #d1d5db;
            position: relative;
            padding-left: 20px;
        }

        .feed-features li:before {
            content: '•';
            color: var(--feed-primary);
            position: absolute;
            left: 0;
        }

        .feed-actions {
            display: flex;
            gap: 15px;
            margin-top: 25px;
            padding-top: 20px;
            border-top: 1px solid rgba(64, 224, 208, 0.2);
        }

        .feed-button {
            flex: 1;
            padding: 12px 20px;
            background: var(--feed-gradient);
            color: white;
            text-decoration: none;
            border-radius: 10px;
            text-align: center;
            font-weight: 600;
            transition: all 0.3s ease;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
        }

        .feed-button:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 25px var(--feed-shadow);
        }

        .feed-button.secondary {
            background: rgba(64, 224, 208, 0.1);
            border: 1px solid rgba(64, 224, 208, 0.3);
            color: #40e0d0;
        }

        .feed-button.secondary:hover {
            background: rgba(64, 224, 208, 0.2);
            border-color: rgba(64, 224, 208, 0.5);
        }

        .info-section {
            background: rgba(10, 14, 39, 0.7);
            border: 2px solid rgba(64, 224, 208, 0.2);
            border-radius: 20px;
            padding: 30px;
            backdrop-filter: blur(15px);
            margin-bottom: 40px;
        }

        .info-section h3 {
            color: #40e0d0;
            margin-bottom: 20px;
            font-size: 20px;
        }

        .info-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
        }

        .info-item {
            padding: 15px;
            background: rgba(64, 224, 208, 0.05);
            border: 1px solid rgba(64, 224, 208, 0.2);
            border-radius: 10px;
        }

        .info-item h4 {
            color: #40e0d0;
            margin-bottom: 8px;
            font-size: 16px;
        }

        .info-item p {
            color: #d1d5db;
            font-size: 14px;
        }

        @media (max-width: 768px) {
            .feeds-grid {
                grid-template-columns: 1fr;
                gap: 20px;
            }
            
            .feed-actions {
                flex-direction: column;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📡 Fire22 Dashboard Feeds</h1>
        <div style="color: #9ca3af; font-size: 16px; margin-top: 10px;">
            Real-time RSS & Atom feeds for error codes, system alerts, and monitoring
        </div>
    </div>

    <div class="container">
        <nav class="breadcrumb">
            <a href="../dashboard.html">🏠 Dashboard</a>
            <span class="breadcrumb-separator">›</span>
            <a href="../departments/">🏢 Departments</a>
            <span class="breadcrumb-separator">›</span>
            <span class="breadcrumb-current">📡 Feeds</span>
        </nav>

        <div class="feeds-grid">
            <!-- RSS Feed -->
            <div class="feed-card feed-rss">
                <div class="feed-header">
                    <div class="feed-icon">📡</div>
                    <div class="feed-title">
                        <div class="feed-name">RSS 2.0 Feed</div>
                        <div class="feed-description">Standard RSS format with rich content and HTML descriptions</div>
                    </div>
                </div>
                
                <div class="feed-details">
                    <p><strong>Format:</strong> RSS 2.0 with Dublin Core extensions</p>
                    <p><strong>Content Type:</strong> application/rss+xml</p>
                    <p><strong>Update Frequency:</strong> Real-time (TTL: 60 minutes)</p>
                    <p><strong>Compatibility:</strong> Most RSS readers and feed aggregators</p>
                </div>

                <div class="feed-features">
                    <h4>🔧 RSS Features:</h4>
                    <ul>
                        <li>Rich HTML content with formatting</li>
                        <li>Departmental assignments and contacts</li>
                        <li>Command-line diagnostic tools</li>
                        <li>Error severity indicators</li>
                        <li>Dublin Core metadata</li>
                        <li>Business impact assessments</li>
                    </ul>
                </div>

                <div class="feed-actions">
                    <a href="error-codes-rss.xml" class="feed-button">
                        📡 Subscribe RSS
                    </a>
                    <a href="error-codes-rss.xml" class="feed-button secondary" target="_blank">
                        👁️ Preview Feed
                    </a>
                </div>
            </div>

            <!-- Atom Feed -->
            <div class="feed-card feed-atom">
                <div class="feed-header">
                    <div class="feed-icon">⚛️</div>
                    <div class="feed-title">
                        <div class="feed-name">Atom 1.0 Feed</div>
                        <div class="feed-description">Modern Atom format with structured content and metadata</div>
                    </div>
                </div>
                
                <div class="feed-details">
                    <p><strong>Format:</strong> Atom 1.0 with full metadata</p>
                    <p><strong>Content Type:</strong> application/atom+xml</p>
                    <p><strong>Update Frequency:</strong> Real-time updates</p>
                    <p><strong>Compatibility:</strong> Modern feed readers and applications</p>
                </div>

                <div class="feed-features">
                    <h4>⚛️ Atom Features:</h4>
                    <ul>
                        <li>Structured XML with precise semantics</li>
                        <li>Enhanced metadata and timestamps</li>
                        <li>Author information and categories</li>
                        <li>Unique entry identifiers</li>
                        <li>Better content type handling</li>
                        <li>Advanced feed relationship links</li>
                    </ul>
                </div>

                <div class="feed-actions">
                    <a href="error-codes-atom.xml" class="feed-button">
                        ⚛️ Subscribe Atom
                    </a>
                    <a href="error-codes-atom.xml" class="feed-button secondary" target="_blank">
                        👁️ Preview Feed
                    </a>
                </div>
            </div>

            <!-- Team Announcements Feed -->
            <div class="feed-card feed-announcements">
                <div class="feed-header">
                    <div class="feed-icon">🏢</div>
                    <div class="feed-title">
                        <div class="feed-name">Team Announcements</div>
                        <div class="feed-description">Official Fire22 team announcements and leadership updates</div>
                    </div>
                </div>
                
                <div class="feed-details">
                    <p><strong>Format:</strong> RSS 2.0 & Atom 1.0</p>
                    <p><strong>Content Type:</strong> Team updates and appointments</p>
                    <p><strong>Update Frequency:</strong> As needed (TTL: 60 minutes)</p>
                    <p><strong>Latest:</strong> Vinny2times appointed Head of VIP Management</p>
                </div>

                <div class="feed-features">
                    <h4>🏢 Announcement Features:</h4>
                    <ul>
                        <li>Leadership appointments and changes</li>
                        <li>Department restructuring updates</li>
                        <li>Team member introductions</li>
                        <li>VIP management communications</li>
                        <li>Organizational milestones</li>
                        <li>Contact information for new roles</li>
                    </ul>
                </div>

                <div class="feed-actions">
                    <a href="team-announcements-rss.xml" class="feed-button">
                        📡 Subscribe RSS
                    </a>
                    <a href="team-announcements-atom.xml" class="feed-button">
                        ⚛️ Subscribe Atom
                    </a>
                    <a href="team-announcements-rss.xml" class="feed-button secondary" target="_blank">
                        👁️ Preview Feed
                    </a>
                </div>
            </div>
        </div>

        <!-- Information Section -->
        <div class="info-section">
            <h3>📊 Feed Information & Usage</h3>
            <div class="info-grid">
                <div class="info-item">
                    <h4>🎯 Content Coverage</h4>
                    <p>9 documented error codes across System (E1xxx), Database (E2xxx), API (E3xxx), Network (E4xxx), Fire22 (E7xxx), and Telegram (E8xxx) categories</p>
                </div>
                <div class="info-item">
                    <h4>🏢 Departments</h4>
                    <p>Technology Department 💻, Operations Department ⚙️, and Customer Support Department 🎧 with clear ownership assignments</p>
                </div>
                <div class="info-item">
                    <h4>🔄 Updates</h4>
                    <p>Real-time feed updates when error codes are added, modified, or resolved. TTL set to 60 minutes for optimal caching</p>
                </div>
                <div class="info-item">
                    <h4>📱 Integration</h4>
                    <p>Compatible with popular feed readers: Feedly, Inoreader, NewsBlur, and custom monitoring systems</p>
                </div>
            </div>
        </div>

        <!-- How to Use Section -->
        <div class="info-section">
            <h3>🔧 How to Use These Feeds</h3>
            
            <h4 style="color: #40e0d0; margin: 20px 0 10px 0;">📱 Feed Reader Applications</h4>
            <p style="color: #d1d5db; margin-bottom: 15px;">Subscribe to either feed URL in your preferred RSS/Atom reader:</p>
            <pre style="background: rgba(0, 0, 0, 0.3); padding: 15px; border-radius: 8px; color: #40e0d0; margin-bottom: 20px; font-size: 14px;">
RSS:  https://dashboard-worker.nolarose2503.workers.dev/src/feeds/error-codes-rss.xml
Atom: https://dashboard-worker.nolarose2503.workers.dev/src/feeds/error-codes-atom.xml
            </pre>

            <h4 style="color: #40e0d0; margin: 20px 0 10px 0;">⚙️ System Integration</h4>
            <p style="color: #d1d5db; margin-bottom: 15px;">Monitor feeds programmatically for automated alerting:</p>
            <pre style="background: rgba(0, 0, 0, 0.3); padding: 15px; border-radius: 8px; color: #e5e7eb; margin-bottom: 20px; font-size: 14px;">
# Fetch and parse RSS feed
curl -s https://dashboard-worker.nolarose2503.workers.dev/src/feeds/error-codes-rss.xml | xmllint --format -

# Monitor for critical errors
curl -s [feed-url] | grep -i "CRITICAL" && echo "Alert: Critical error detected!"

# Integration with monitoring systems
wget -q -O - [feed-url] | your-monitoring-parser
            </pre>

            <h4 style="color: #40e0d0; margin: 20px 0 10px 0;">🚨 Alerting Setup</h4>
            <p style="color: #d1d5db;">Configure your monitoring systems to watch for:</p>
            <ul style="color: #d1d5db; margin-left: 20px; margin-top: 10px;">
                <li>🔴 <strong>CRITICAL</strong> errors (E1001, E2001, E7001) - Immediate alerts</li>
                <li>🟡 <strong>ERROR</strong> level issues - Standard notifications</li>
                <li>⚠️ <strong>WARNING</strong> level events - Low priority alerts</li>
            </ul>
        </div>

        <!-- Quick Actions -->
        <div style="text-align: center; margin-top: 40px;">
            <div style="display: flex; justify-content: center; gap: 20px; flex-wrap: wrap;">
                <a href="../departments/" style="
                    padding: 15px 25px;
                    background: linear-gradient(135deg, #40e0d0, #64ffda);
                    color: #0a0e27;
                    text-decoration: none;
                    border-radius: 12px;
                    font-weight: 600;
                    transition: transform 0.3s ease;
                " onmouseover="this.style.transform='translateY(-2px)'" 
                   onmouseout="this.style.transform=''">
                    🏢 View Departments
                </a>
                <a href="../dashboard.html" style="
                    padding: 15px 25px;
                    background: rgba(64, 224, 208, 0.1);
                    border: 2px solid rgba(64, 224, 208, 0.3);
                    color: #40e0d0;
                    text-decoration: none;
                    border-radius: 12px;
                    font-weight: 600;
                    transition: all 0.3s ease;
                " onmouseover="this.style.borderColor='rgba(64, 224, 208, 0.6)'; this.style.background='rgba(64, 224, 208, 0.2)'" 
                   onmouseout="this.style.borderColor='rgba(64, 224, 208, 0.3)'; this.style.background='rgba(64, 224, 208, 0.1)'">
                    🏠 Main Dashboard
                </a>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            console.log('📡 Fire22 Dashboard Feeds page loaded');
            console.log('🔗 RSS Feed: error-codes-rss.xml');
            console.log('⚛️ Atom Feed: error-codes-atom.xml');
            
            // Add feed validation
            const feeds = ['error-codes-rss.xml', 'error-codes-atom.xml'];
            feeds.forEach(async (feedUrl) => {
                try {
                    const response = await fetch(feedUrl);
                    if (response.ok) {
                        console.log(\`✅ \${feedUrl} - Feed available\`);
                    } else {
                        console.warn(\`⚠️ \${feedUrl} - Response: \${response.status}\`);
                    }
                } catch (error) {
                    console.error(\`❌ \${feedUrl} - Error:\`, error.message);
                }
            });
        });
    </script>
</body>
</html>`,
};

export function getFeedContent(filename: string): string | undefined {
  return feedsContent[filename];
}

export function getAvailableFeeds(): string[] {
  return Object.keys(feedsContent);
}
