/**
 * Fire22 Admin Routes
 * Auto-generated by consolidation script
 */
export declare const adminRoutes: import('itty-router').RouterType<
  import('itty-router').Route,
  any[]
>;
//# sourceMappingURL=admin.routes.d.ts.map
