/**
 * Fire22 Admin Routes
 * Auto-generated by consolidation script
 */

import { Router } from 'itty-router';
import { validate } from '../middleware/validate.middleware';
import { authorize } from '../middleware/authorize.middleware';
import * as controller from '../controllers/admin.controller';
import * as schemas from '@fire22/validator/schemas';

const router = Router({ base: '/admin' });

// /api/admin/settle-wager (from index.ts:2738)
router.post('/settle-wager', authorize(['admin.wager.settle']), controller.settleWager);

// /api/admin/bulk-settle (from index.ts:2777)
router.post('/bulk-settle', authorize(['admin.wager.settle']), controller.bulkSettle);

// /api/admin/pending-settlements (from index.ts:2824)
router.get(
  '/pending-settlements',
  authorize(['admin.wager.settle']),
  controller.pendingSettlements
);

// /api/admin/void-wager (from index.ts:2949)
router.post('/void-wager', authorize(['admin.*']), controller.voidWager);

// /api/admin/create-customer (from index.ts:4504)
router.post('/create-customer', authorize(['admin.customer.manage']), controller.createCustomer);

// /api/admin/process-deposit (from index.ts:4541)
router.post('/process-deposit', authorize(['admin.financial.deposit']), controller.processDeposit);

// /api/admin/agent-configs-dashboard (from index.ts:5286)
router.get('/agent-configs-dashboard', authorize(['admin.*']), controller.agentConfigsDashboard);

// /api/admin/import-customers (from index.ts:7436)
router.post('/import-customers', authorize(['admin.customer.manage']), controller.importCustomers);

// /api/admin/sync-fire22 (from index.ts:7502)
router.post('/sync-fire22', authorize(['admin.system.sync']), controller.syncFire22);

// /api/admin/debug/cache-stats (from index.ts:7946)
router.get('/debug/cache-stats', authorize(['admin.*']), controller.debugCacheStats);

export const adminRoutes = router;
