/**
 * Fire22 Auth Routes
 * Auto-generated by consolidation script
 */
import { Router } from 'itty-router';
import * as controller from '../controllers/auth.controller';
const router = Router({ base: '/auth' });
// /api/auth/login (from index.ts:2601)
router.post('/login', controller.login);
// /api/auth/logout (from index.ts:2655)
router.post('/logout', controller.logout);
// /api/auth/verify (from index.ts:2665)
router.get('/verify', controller.verify);
export const authRoutes = router;
//# sourceMappingURL=auth.routes.js.map
