/**
 * Fire22 Auth Routes
 * Auto-generated by consolidation script
 */
export declare const authRoutes: import('itty-router').RouterType<
  import('itty-router').Route,
  any[]
>;
//# sourceMappingURL=auth.routes.d.ts.map
