/**
 * Fire22 Customer Routes
 * Auto-generated by consolidation script
 */
export declare const customerRoutes: import('itty-router').RouterType<
  import('itty-router').Route,
  any[]
>;
//# sourceMappingURL=customer.routes.d.ts.map
