/**
 * Fire22 Customer Routes
 * Auto-generated by consolidation script
 */
import { Router } from 'itty-router';
import { authorize } from '../middleware/authorize.middleware';
import * as controller from '../controllers/customer.controller';
const router = Router({ base: '/customer' });
// /api/customer/getHeriarchy (from server.js:954)
router.post('/getHeriarchy', authorize(['customer.*']), controller.getHeriarchy);
export const customerRoutes = router;
//# sourceMappingURL=customer.routes.js.map
