/**
 * Fire22 Financial Routes
 * Auto-generated by consolidation script
 */
export declare const financialRoutes: import('itty-router').RouterType<
  import('itty-router').Route,
  any[]
>;
//# sourceMappingURL=financial.routes.d.ts.map
