/**
 * Fire22 Financial Routes
 * Auto-generated by consolidation script
 */

import { Router } from 'itty-router';
import { validate } from '../middleware/validate.middleware';
import { authorize } from '../middleware/authorize.middleware';
import * as controller from '../controllers/financial.controller';
import * as schemas from '@fire22/validator/schemas';

const router = Router({ base: '/financial' });

// /api/withdrawals/request (from index.ts:2993)
router.post(
  '//api/withdrawals/request',
  authorize(['financial.*']),
  controller.apiWithdrawalsRequest
);

// /api/withdrawals/approve (from index.ts:3069)
router.post(
  '//api/withdrawals/approve',
  authorize(['financial.*']),
  controller.apiWithdrawalsApprove
);

// /api/withdrawals/complete (from index.ts:3129)
router.post(
  '//api/withdrawals/complete',
  authorize(['financial.*']),
  controller.apiWithdrawalsComplete
);

// /api/withdrawals/reject (from index.ts:3191)
router.post(
  '//api/withdrawals/reject',
  authorize(['financial.*']),
  controller.apiWithdrawalsReject
);

// /api/withdrawals/pending (from index.ts:3246)
router.get(
  '//api/withdrawals/pending',
  authorize(['financial.*']),
  controller.apiWithdrawalsPending
);

// /api/withdrawals (from index.ts:3285)
router.get('//api/withdrawals', authorize(['financial.*']), controller.apiWithdrawals);

// /api/queue/init (from index.ts:8057)
router.post('//api/queue/init', authorize(['financial.*']), controller.apiQueueInit);

// /api/queue/withdrawal (from index.ts:8113)
router.post('//api/queue/withdrawal', authorize(['financial.*']), controller.apiQueueWithdrawal);

// /api/queue/deposit (from index.ts:8173)
router.post('//api/queue/deposit', authorize(['financial.*']), controller.apiQueueDeposit);

// /api/queue/stats (from index.ts:8220)
router.get('//api/queue/stats', authorize(['financial.*']), controller.apiQueueStats);

// /api/queue/items (from index.ts:8244)
router.get('//api/queue/items', authorize(['financial.*']), controller.apiQueueItems);

// /api/queue/opportunities (from index.ts:8276)
router.get(
  '//api/queue/opportunities',
  authorize(['financial.*']),
  controller.apiQueueOpportunities
);

// /api/queue/process (from index.ts:8337)
router.post('//api/queue/process', authorize(['financial.*']), controller.apiQueueProcess);

// /api/queue/complete (from index.ts:8361)
router.post('//api/queue/complete', authorize(['financial.*']), controller.apiQueueComplete);

export const financialRoutes = router;
