/**
 * Fire22 Health Routes
 * Auto-generated by consolidation script
 */
export declare const healthRoutes: import('itty-router').RouterType<
  import('itty-router').Route,
  any[]
>;
//# sourceMappingURL=health.routes.d.ts.map
