/**
 * Fire22 Manager Routes
 * Auto-generated by consolidation script
 */
export declare const managerRoutes: import('itty-router').RouterType<
  import('itty-router').Route,
  any[]
>;
//# sourceMappingURL=manager.routes.d.ts.map
