/**
 * Fire22 Other Routes
 * Auto-generated by consolidation script
 */
export declare const otherRoutes: import('itty-router').RouterType<
  import('itty-router').Route,
  any[]
>;
//# sourceMappingURL=other.routes.d.ts.map
