#!/bin/bash

# Fire22 Personal Subdomains - Environment Setup Script
# This script helps you configure Cloudflare credentials for deployment

echo "🔧 Fire22 Personal Subdomains - Environment Setup"
echo "=================================================="
echo ""

# Check if .env file exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled. Using existing .env file."
        exit 0
    fi
fi

echo "📋 You'll need the following Cloudflare information:"
echo "   1. Account ID (from Cloudflare Dashboard → Account Home)"
echo "   2. API Token (from Cloudflare Dashboard → My Profile → API Tokens)"
echo "   3. Zone ID (from Cloudflare Dashboard → fire22.workers.dev → Overview)"
echo ""

# Get Cloudflare Account ID
read -p "Enter your Cloudflare Account ID: " CLOUDFLARE_ACCOUNT_ID
if [ -z "$CLOUDFLARE_ACCOUNT_ID" ]; then
    echo "❌ Account ID is required"
    exit 1
fi

# Get Cloudflare API Token
read -p "Enter your Cloudflare API Token: " CLOUDFLARE_API_TOKEN
if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
    echo "❌ API Token is required"
    exit 1
fi

# Get Zone ID
read -p "Enter your Zone ID for fire22.workers.dev: " CLOUDFLARE_ZONE_ID
if [ -z "$CLOUDFLARE_ZONE_ID" ]; then
    echo "❌ Zone ID is required"
    exit 1
fi

# Create .env file
cat > .env << EOF
# Cloudflare Configuration for Fire22 Personal Subdomains
# Generated by setup-env.sh on $(date)

# Your Cloudflare Account ID
CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID

# Cloudflare API Token
CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN

# Zone ID for fire22.workers.dev
CLOUDFLARE_ZONE_ID=$CLOUDFLARE_ZONE_ID

# Environment settings
ENVIRONMENT=production
FIRE22_BRAND=enabled
EOF

echo ""
echo "✅ .env file created successfully!"
echo ""
echo "🔐 Your Cloudflare credentials are now configured."
echo ""
echo "🚀 Ready to deploy! Run the following commands:"
echo ""
echo "   # Load environment variables"
echo "   source .env"
echo ""
echo "   # Deploy the personal subdomains infrastructure"
echo "   bun run scripts/deploy-worker.ts"
echo ""
echo "   # Or use the automated setup script"
echo "   bun run setup"
echo ""
echo "🎯 This will deploy:"
echo "   • Vinny2Times VIP subdomain (CRITICAL - 24hr deadline)"
echo "   • All executive and employee personal subdomains"
echo "   • Wildcard DNS configuration"
echo "   • SSL certificates and security"
echo ""
echo "📞 Need help? Contact:"
echo "   • Technical: Chris Brown (CTO) - chris.brown@tech.fire22"
echo "   • Project: Jennifer Adams (HR) - jennifer.adams@hr.fire22"
