#!/bin/bash
# Fire22 Registry Wrapper for bunx
# Auto-generated by fix-registry-connection.ts

# Function to try bunx with fallback registries
fire22_bunx() {
    local package="$1"
    shift
    local args="$@"
    
    # Primary registry attempt
    echo "🚀 Attempting with primary registry..."
    if timeout 30s bun x "$package" $args 2>/dev/null; then
        return 0
    fi
    
    # Fallback to NPM registry
    echo "🔄 Falling back to NPM registry..."
    BUN_REGISTRY="https://registry.npmjs.org/" timeout 30s bun x "$package" $args 2>/dev/null && return 0
    
    # Fallback to Yarn registry
    echo "🔄 Falling back to Yarn registry..."
    BUN_REGISTRY="https://registry.yarnpkg.com/" timeout 30s bun x "$package" $args 2>/dev/null && return 0
    
    # Last resort: direct npm
    echo "🔄 Last resort: using npx..."
    if command -v npx >/dev/null 2>&1; then
        npx "$package" $args
        return $?
    fi
    
    echo "❌ All registry attempts failed. Options:"
    echo "  1. Check network connectivity: ping registry.npmjs.org"
    echo "  2. Try manual install: bun add -g $package"
    echo "  3. Use alternative: npm i -g $package && npx $package"
    echo "  4. Contact system administrator"
    return 1
}

# Call the function with all arguments
fire22_bunx "$@"
