US:
  TRANSACTION:
    BET: "BET"
    WIN: "WIN"
    DEPOSIT: "DEP"
    WITHDRAWAL: "WDR"
    ADJUSTMENT: "ADJ"
    BONUS: "BON"
    FEE: "FEE"

  ACCOUNT:
    CUSTOMER_WALLET: "CUST_WALLET"
    BONUS_ACCOUNT: "BONUS_ACCT"
    FEE_ACCOUNT: "FEE_ACCT"
    REVENUE_ACCOUNT: "REV_ACCT"
    EXPENSE_ACCOUNT: "EXP_ACCT"

  CURRENCY:
    USD: "840"
    EUR: "978"
    GBP: "826"
    CAD: "124"
    AUD: "036"

EU:
  TRANSACTION:
    BET: "GAMING_BET"
    WIN: "GAMING_WIN"
    DEPOSIT: "PAYMENT_IN"
    WITHDRAWAL: "PAYMENT_OUT"
    ADJUSTMENT: "ACCOUNT_ADJ"
    BONUS: "BONUS_CREDIT"
    FEE: "SERVICE_FEE"

  ACCOUNT:
    CUSTOMER_WALLET: "CUSTOMER_WALLET"
    BONUS_ACCOUNT: "BONUS_WALLET"
    FEE_ACCOUNT: "FEE_WALLET"
    REVENUE_ACCOUNT: "REVENUE_ACCOUNT"
    EXPENSE_ACCOUNT: "EXPENSE_ACCOUNT"

  CURRENCY:
    USD: "USD"
    EUR: "EUR"
    GBP: "GBP"
    CAD: "CAD"
    AUD: "AUD"

UK:
  TRANSACTION:
    BET: "STAKE"
    WIN: "PAYMENT"
    DEPOSIT: "DEPOSIT"
    WITHDRAWAL: "WITHDRAWAL"
    ADJUSTMENT: "ADJUSTMENT"
    BONUS: "BONUS"
    FEE: "CHARGE"

  ACCOUNT:
    CUSTOMER_WALLET: "CUSTOMER_ACCOUNT"
    BONUS_ACCOUNT: "BONUS_ACCOUNT"
    FEE_ACCOUNT: "FEE_ACCOUNT"
    REVENUE_ACCOUNT: "REVENUE_ACCOUNT"
    EXPENSE_ACCOUNT: "EXPENSE_ACCOUNT"

  CURRENCY:
    USD: "USD"
    EUR: "EUR"
    GBP: "GBP"
    CAD: "CAD"
    AUD: "AUD"
