/**
 * Fire22 Health Routes
 * Auto-generated by consolidation script
 */

import { Router } from 'itty-router';
import { validate } from '../middleware/validate.middleware';
import { authorize } from '../middleware/authorize.middleware';
import * as controller from '../controllers/health.controller';
import * as schemas from '@fire22/validator/schemas';

const router = Router({ base: '/health' });

// /api/test/fire22 (from index.ts:5665)
router.get('//api/test/fire22', controller.apiTestFire22);

// /api/test-deployment (from index.ts:6008)
router.get('//api/test-deployment', controller.apiTestDeployment);

// /api/health/permissions (from index.ts:6135)
router.get('/permissions', controller.permissions);

// /api/health/permissions-matrix (from index.ts:6358)
router.get('/permissions-matrix', controller.permissionsMatrix);

// /api/health/system (from index.ts:6939)
router.get('/system', controller.system);

// /api/matrix/health (from index.ts:8394)
router.get('//api/matrix/health', controller.apiMatrixHealth);

// /health (from server.js:1284)
router.get('//health', controller.health);

export const healthRoutes = router;
