/**
 * Fire22 Manager Routes
 * Auto-generated by consolidation script
 */

import { Router } from 'itty-router';
import { validate } from '../middleware/validate.middleware';
import { authorize } from '../middleware/authorize.middleware';
import * as controller from '../controllers/manager.controller';
import * as schemas from '@fire22/validator/schemas';

const router = Router({ base: '/manager' });

// /api/manager/getWeeklyFigureByAgent (from index.ts:3712)
router.post(
  '/getWeeklyFigureByAgent',
  authorize(['manager.reports.weekly']),
  controller.getWeeklyFigureByAgent
);

// /api/manager/getPending (from index.ts:3782)
router.post('/getPending', authorize(['manager.*']), controller.getPending);

// /api/manager/getTransactions (from index.ts:4001)
router.get('/getTransactions', authorize(['manager.*']), controller.getTransactions);

// /api/manager/getCustomers (from index.ts:4071)
router.get('/getCustomers', authorize(['manager.customer.list']), controller.getCustomers);

// /api/manager/getLiveActivity (from index.ts:4212)
router.get('/getLiveActivity', authorize(['manager.*']), controller.getLiveActivity);

// /api/manager/getLiveWagers (from index.ts:5387)
router.get('/getLiveWagers', authorize(['manager.wager.view_live']), controller.getLiveWagers);

// /api/manager/getAgentPerformance (from index.ts:5420)
router.get(
  '/getAgentPerformance',
  authorize(['manager.agent.performance']),
  controller.getAgentPerformance
);

// /api/manager/getWagerAlerts (from index.ts:5450)
router.get('/getWagerAlerts', authorize(['manager.*']), controller.getWagerAlerts);

// /api/manager/getVIPCustomers (from index.ts:5481)
router.get('/getVIPCustomers', authorize(['manager.*']), controller.getVIPCustomers);

// /api/manager/getBetTicker (from index.ts:5524)
router.get('/getBetTicker', authorize(['manager.*']), controller.getBetTicker);

// /api/manager/getSportAnalytics (from index.ts:5554)
router.get('/getSportAnalytics', authorize(['manager.*']), controller.getSportAnalytics);

// /api/manager/getCustomerDetails (from index.ts:5613)
router.get('/getCustomerDetails', authorize(['manager.*']), controller.getCustomerDetails);

// /api/manager/getSettings (from index.ts:7587)
router.get('/getSettings', authorize(['manager.*']), controller.getSettings);

// /api/manager/getAgentKPI (from index.ts:7703)
router.get('/getAgentKPI', authorize(['manager.*']), controller.getAgentKPI);

// /api/manager/getCustomersByAgent (from index.ts:7751)
router.get(
  '/getCustomersByAgent',
  authorize(['manager.customer.list']),
  controller.getCustomersByAgent
);

// /api/manager/getWagersByAgent (from index.ts:7791)
router.get('/getWagersByAgent', authorize(['manager.*']), controller.getWagersByAgent);

// /api/manager/getPending (from index.ts:7833)
router.get('/getPending', authorize(['manager.*']), controller.getPending);

// /api/manager/getWeeklyFigureByAgent (from index.ts:7991)
router.get(
  '/getWeeklyFigureByAgent',
  authorize(['manager.reports.weekly']),
  controller.getWeeklyFigureByAgent
);

// /api/manager/getWeeklyFigureByAgentLite - Lightweight version for faster loading
router.post(
  '/getWeeklyFigureByAgentLite',
  authorize(['manager.reports.weekly']),
  controller.getWeeklyFigureByAgentLite
);

// /api/manager/getLiveWagers (from server.js:237)
router.post('/getLiveWagers', authorize(['manager.wager.view_live']), controller.getLiveWagers);

// /api/manager/getCustomerAdmin (from server.js:381)
router.post('/getCustomerAdmin', authorize(['manager.*']), controller.getCustomerAdmin);

// /api/manager/getCustomerSummary (from server.js:640)
router.get('/getCustomerSummary', authorize(['manager.*']), controller.getCustomerSummary);

// /api/manager/getBets (from server.js:821)
router.get('/getBets', authorize(['manager.*']), controller.getBets);

// /api/manager/getAgentPerformance (from server.js:903)
router.post(
  '/getAgentPerformance',
  authorize(['manager.agent.performance']),
  controller.getAgentPerformance
);

// /api/manager/getCryptoInfo - Get cryptocurrency information
router.post('/getCryptoInfo', authorize(['manager.*']), controller.getCryptoInfo);

// /api/manager/getInfoPlayer - Get player information
router.post('/getInfoPlayer', authorize(['manager.*']), controller.getInfoPlayer);

export const managerRoutes = router;
