name: Dependency Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Mondays
    - cron: '0 9 * * 1'

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install --frozen-lockfile
    
    - name: Run dependency analysis
      run: bun run deps:analyze
      
    - name: Check for version conflicts
      run: |
        if bun why "semver*" | grep -q "semver@.*semver@"; then
          echo "⚠️ Version conflicts detected"
          bun why "semver*" | grep "semver@" | head -5
          echo "::warning::Multiple semver versions detected - consider consolidation"
        else
          echo "✅ No version conflicts detected"
        fi
    
    - name: Analyze bundle size impact
      run: |
        echo "📊 Bundle size analysis:"
        bun why "@types/*" --depth 1 | grep -c "@types/" | xargs echo "  @types packages:"
        bun why "webpack*" --depth 1 | grep -c "webpack" | xargs echo "  webpack packages:"
    
    - name: Upload analysis results
      uses: actions/upload-artifact@v4
      with:
        name: dependency-analysis
        path: dependency-analysis-report.md
